language: cpp
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev libcurl4-openssl-dev autoconf automake pkg-config m4
compiler:
  - gcc
  - clang
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8

script:
  - ./autogen.sh
  - ./configure
  - make
